site_name: koolstof
site_author: Matthew P. Humphreys
site_description: Processing measurements of dissolved inorganic carbon
site_url: https://koolstof.hseao3.group/
copyright: Copyright &copy; 2020–2025  M.P. Humphreys  (GNU GPLv3)

repo_name: mvdh7/koolstof
repo_url: https://github.com/mvdh7/koolstof

nav:
  - Overview & installation: index.md
  - VINDTA DIC processing: vindta.md
  - Version history: versions.md

theme:
  name: material
  language: en
  palette:
    scheme: default
    primary: black
    accent: deep orange
  font:
    text: Roboto Slab
    code: Roboto Mono

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

