[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "koolstof"
description = "Processing measurements of dissolved inorganic carbon"
readme = "README.md"
requires-python = ">=3.11"
classifiers =[
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Oceanography",
    "Topic :: Scientific/Engineering :: Visualization",
]
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "scipy",
]
dynamic = ["version"]

[tool.setuptools.packages.find]
include = ["koolstof*"]

[tool.setuptools.dynamic]
version = {attr = "koolstof.meta.__version__"}

[tool.ruff]
line-length = 79

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = false
lines-after-imports = 2

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
