import pandas as pd
from matplotlib import dates as mdates

mapper_dbs = {
    "run type": "run_type",
    "i.s. temp.": "temperature_insitu",
    "sample mass": "mass_sample",
    "rep#": "rep",
    "CT": "dic",
    "factor CT": "dic_factor",
    "CV (µmol)": "cv_micromol",
    "CV (%)": "cv_percent",
    "last CRM CT": "lastcrm_dic_measured",
    "cert. CRM CT": "lastcrm_dic_certified",
    "CRM batch": "lastcrm_batch",
    "calc. mode": "mode_calculation",
    "integ. mode": "mode_integration",
    "Lat.": "latitude",
    "Long.": "longitude",
    "area#1": "area_1",
    "area#2": "area_2",
    "area#3": "area_3",
    "area#4": "area_4",
}


def read_dbs(filepath_or_buffer, encoding="unicode_escape", na_values="none", **kwargs):
    """Import the dbs file generated by a Marianda AIRICA as a pandas DataFrame.
    Any kwargs are passed to pandas.read_table.
    """
    dbs = pd.read_table(
        filepath_or_buffer, encoding=encoding, na_values=na_values, **kwargs
    )
    dbs.rename(mapper=mapper_dbs, axis=1, inplace=True)
    dbs.drop(columns="Unnamed: 32", inplace=True)
    dbs["datetime"] = pd.to_datetime(
        dbs.apply(lambda x: " ".join((x.date, x.time)), axis=1)
    )
    dbs["datenum"] = mdates.date2num(dbs.datetime)
    return dbs


mapper_LI7000 = {
    "Time": "datetime",
    "CO2B um/m": "x_CO2",
    "H2OB mm/m": "x_H2O",
    "T C": "temperature",
    "P kPa": "pressure",
    "RH %": "humidity_relative",
    "Flow V": "flow_voltage",
}


def read_LI7000(filepath_or_buffer, skiprows=2, **kwargs):
    """Import the text files recorded by a LI-COR LI-7000 as a pandas DataFrame.
    Any kwargs are passed to pandas.read_table.
    """
    licor = pd.read_table(filepath_or_buffer, skiprows=skiprows, **kwargs)
    licor.rename(mapper=mapper_LI7000, axis=1, inplace=True)
    licor["datetime"] = pd.to_datetime(licor.datetime)
    licor["datenum"] = mdates.date2num(licor.datetime)
    return licor
