name: Documentation
on:
  push:
    paths:
      - mkdocs.yml
      - docs/**
    branches:
      - v1
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install zensical
      - run: zensical build --clean
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site
      - uses: actions/deploy-pages@v4
        id: deployment
      - name: Update CNAME file
        run: |
          echo "koolstof.hseao3.group" > CNAME
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add CNAME
          git commit -m "Create CNAME"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
